import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import { runScanCommand, type RepoMapDocument } from "../src/commands/scan.js";
import { pathExists } from "../src/infra/fs.js";
import type { GraphifySnapshotResult } from "../src/commands/graphify-snapshot.js";

const tempRoots: string[] = [];

afterEach(async () => {
  while (tempRoots.length > 0) {
    const target = tempRoots.pop();
    if (target) {
      await rm(target, { recursive: true, force: true });
    }
  }
});

async function makeTempWorkspace(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "codex-scan-"));
  tempRoots.push(root);
  return root;
}

function fakeGraphifyResult(targetPath: string): GraphifySnapshotResult {
  return {
    ok: true,
    message: "ok",
    summary: {
      target_path: targetPath,
      profile: "source-only",
      tool_dir: "C:/tools/graphify",
      helper_python: "C:/tools/graphify/.venv/Scripts/python.exe",
      package_installed: false,
      ignore_path: join(targetPath, ".graphifyignore"),
      ignore_action: "preserved",
      graphify_out_path: join(targetPath, "graphify-out"),
      graph_json_path: join(targetPath, "graphify-out", "graph.json"),
      report_path: join(targetPath, "graphify-out", "GRAPH_REPORT.md"),
      html_path: join(targetPath, "graphify-out", "graph.html"),
      elapsed_ms: 10,
      metrics: {
        files: 3,
        approximate_words: 100,
        nodes: 7,
        edges: 6,
        communities: 2,
        extraction_summary: "- Extraction: ok",
        god_nodes: ["1. `src/index.ts`"],
      },
      next_steps: [],
    },
  };
}

describe("scan", () => {
  it("writes a repo map after Graphify succeeds and leaves TEAM_GUIDE untouched by default", async () => {
    const workspace = await makeTempWorkspace();
    const graphifyCalls: unknown[] = [];
    await mkdir(join(workspace, "src"), { recursive: true });
    await writeFile(join(workspace, "README.md"), "# Demo\n\nA demo repo.\n", "utf8");
    await writeFile(
      join(workspace, "package.json"),
      JSON.stringify({ scripts: { test: "vitest run", build: "tsc -p tsconfig.json" }, dependencies: {} }, null, 2),
      "utf8",
    );
    await writeFile(join(workspace, "src", "index.ts"), "export const ok = true;\n", "utf8");

    const result = await runScanCommand(
      { target: workspace, profile: "source-only" },
      {
        runGraphifySnapshot: async (options) => {
          graphifyCalls.push(options);
          return fakeGraphifyResult(workspace);
        },
        now: () => new Date("2026-04-20T00:00:00.000Z"),
      },
    );

    const repoMapPath = join(workspace, "autonomy", "context", "repo-map.json");
    const repoMap = JSON.parse(await readFile(repoMapPath, "utf8")) as RepoMapDocument;

    expect(result.ok).toBe(true);
    expect(result.summary.repo_map_path).toBe(repoMapPath);
    expect(result.summary.team_guide_action).toBe("skipped");
    expect(graphifyCalls[0]).toMatchObject({ writeIgnore: false });
    expect(repoMap.version).toBe(1);
    expect(repoMap.commands.package_scripts[0]?.scripts).toEqual(["build", "test"]);
    expect(repoMap.commands.verification_candidates).toContain("npm run test");
    expect(repoMap.entrypoints).toContain("src/index.ts");
    expect(await pathExists(join(workspace, "TEAM_GUIDE.md"))).toBe(false);
  });

  it("updates TEAM_GUIDE only when requested", async () => {
    const workspace = await makeTempWorkspace();
    await writeFile(join(workspace, "package.json"), JSON.stringify({ scripts: { test: "vitest run" } }, null, 2), "utf8");

    const result = await runScanCommand(
      { target: workspace, profile: "source-only", updateTeamGuide: true },
      { runGraphifySnapshot: async () => fakeGraphifyResult(workspace), now: () => new Date("2026-04-20T00:00:00.000Z") },
    );
    const teamGuide = await readFile(join(workspace, "TEAM_GUIDE.md"), "utf8");

    expect(result.summary.team_guide_action).toBe("updated");
    expect(teamGuide).toContain("Generated by `codex-autonomy scan --profile source-only --update-team-guide`");
    expect(teamGuide).toContain("autonomy/context/repo-map.json");
  });

  it("does not write repo-map.json when Graphify fails", async () => {
    const workspace = await makeTempWorkspace();

    await expect(runScanCommand(
      { target: workspace, profile: "source-only" },
      {
        runGraphifySnapshot: async () => {
          throw new Error("graphify failed");
        },
      },
    )).rejects.toThrow(/graphify failed/);

    expect(await pathExists(join(workspace, "autonomy", "context", "repo-map.json"))).toBe(false);
  });
});
